backend_programme:
    resource: "@BackendBundle/Controller/ProgrammeController.php"
    type:     annotation

backend_cours:
    resource: "@BackendBundle/Controller/CoursController.php"
    type:     annotation

backend_nutrition:
    resource: "@BackendBundle/Controller/NutritionController.php"
    type:     annotation

backend_jour:
    resource: "@BackendBundle/Controller/JourController.php"
    type:     annotation

frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /

backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /app

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"