<?php

namespace BackendBundle\Repository;

/**
 * NutritionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NutritionRepository extends \Doctrine\ORM\EntityRepository
{
}
